"""
Phase 2 — COI-002 corpus patch
Sections: intent-ontology, authorized-representations, equivalence-relation,
          admissibility-posture, drift-bounds
Run from repo root: python scripts/patch-coi002-phase2.py
Acceptance: python -c "import json; b=json.load(open('data/corpus-bundle.json')); \
  [print(a['id'], len(a['sections'])) for a in b['artifacts']]"
  => UFTAGP-COI-002 shows 5
"""
import json, pathlib

BUNDLE = pathlib.Path("data/corpus-bundle.json")

SECTIONS = [
    {
        "ref": "intent-ontology",
        "heading": "Representational Ontology of Intent",
        "text": (
            "This volume formalizes the trilogy's intent-domain ontology as a representational, "
            "non-operational framework for lawful classification. It constrains intent to authorized "
            "representations only and defines the relations needed to preserve meaning under "
            "transformation: representation classes, intent-domain object, domain equivalence, "
            "interpretation, drift, drift bounds, and trace representability. Conserving, "
            "Non-Conserving, and Refusal (Terminal) are treated as ontology-level outputs rather "
            "than scores or guarantees.\n\n"
            "This trilogy requires a disciplined ontology because ethical language fails most often "
            "where it becomes elastic — where 'intent' is treated as a psychological certainty, a "
            "hidden motive, a narrative after-the-fact, or a permission slip for surveillance. "
            "Accordingly, this volume uses an explicit representational ontology: it constrains what "
            "'intent' is allowed to mean so that interpretation remains stable under pressure, across "
            "architectures, and across regimes — without drifting into mind-reading, identity "
            "inference, or outcome claims.\n\n"
            "Intent (sealed). Within this trilogy, 'intent' denotes authorized representations only. "
            "Authorized representations include only what is explicitly stated and scoped within the "
            "received record — such as explicit policy statements, declared objectives, or declared "
            "prohibitions; contracts, covenants, or binding non-claims; declared constraints; scope "
            "statements; and citation/use constraints. In this trilogy, 'intent' is not treated as a "
            "hidden interior. It is treated as a publicly representable constraint object: what has "
            "been explicitly authorized to be taken as governing language.\n\n"
            "Intent SHALL mean only authorized representations present within the received record. "
            "The set of authorized representations admitted as intent for classification SHALL be "
            "called the intent basis. An intent basis is admissible only when all of the following "
            "hold: the representations are explicit (not implied, suggested, or 'read between the "
            "lines'); the authorization source of each representation is present within the received "
            "record; the scope boundary is stated; and the intent basis is non-contradictory within "
            "the received record.\n\n"
            "Intent SHALL NOT be construed as: a 'true intent' behind a representation; a mental "
            "state, preference, disposition, or psychological attribution; identity-derived intent "
            "(including intent inferred from role, affiliation, demographic attributes, or presumed "
            "motives); behavior-inferred intent (including intent inferred from outputs, usage "
            "patterns, or observed conduct); a latent objective 'really meant' but not stated; or "
            "any substitute meaning introduced to make the doctrine operational, enforceable, "
            "measurable, or outcome-bearing.\n\n"
            "Intent-Domain Object. An intent-domain is the bounded meaning-domain defined by "
            "authorized intent representations admitted under Intent (sealed). It exists so that "
            "conservation classification can be stated without drifting into inference, "
            "operationalization, or outcome-claim capture. Let ID denote the intent-domain object, "
            "comprising: R — the set of authorized representations admitted to the intent basis; "
            "Interp() — an interpretation relation internal to the intent-domain mapping "
            "representations to their admissible meaning commitments; and Auth() — an authorization "
            "predicate delimiting membership in R. This formalization is representational only. It "
            "does not introduce measurement, inference, computation, enforcement, monitoring, "
            "scoring, or mechanism design.\n\n"
            "The intent-domain SHALL be treated as a closed jurisdictional object: membership is "
            "bounded (only representations admitted by Auth() are members of R); meaning is bounded "
            "(only meaning commitments admitted by Interp() are admissible); scope is bounded (only "
            "what is explicitly included in the received record's scope statements is governed); and "
            "inference is prohibited (no membership, interpretation, or scope expansion SHALL be "
            "justified by identity inference, mental-state inference, behavioral inference, "
            "retrospective motive attribution, or narrative substitution). The intent-domain is not "
            "'what the author truly meant.' It is what is lawfully admitted as meaning within "
            "authorized representations.\n\n"
            "Where ID cannot be formed without prohibited inference — where Auth() cannot be "
            "satisfied without importing identity, mental-state, or behavioral inference; where "
            "Interp() would require operational substitution to 'make meaning real'; or where scope "
            "cannot be bounded without narrative supplementation — the classification outcome SHALL "
            "be Refusal (Terminal). Refusal is terminal."
        ),
    },
    {
        "ref": "authorized-representations",
        "heading": "Authorized Representation Classes",
        "text": (
            "Within this ontology, an authorized representation is any explicit artifact admissibly "
            "admitted to the sealed intent basis under Intent (sealed) and Volume I's admissibility "
            "constraints. An authorized representation is a representational object only. It is not "
            "an interface. It is not a mechanism. It is not a monitoring posture. It is not an "
            "enforcement regime. It is not an outcome claim. It is the lawful substrate by which "
            "intent may be represented without inference.\n\n"
            "Admissibility Conditions (Binding). A representation SHALL be treated as authorized "
            "only if all of the following conditions hold:\n"
            "Explicitness: the representation is stated, not implied. No 'read between the lines' "
            "supplementation is permitted.\n"
            "Attribution: the representation is attributable to an authorization source within the "
            "received record.\n"
            "Scope determinacy: the representation's scope boundary is stated or determinable from "
            "the representation itself without importing inference.\n"
            "Non-inferential interpretability: the representation can be interpreted as a "
            "representational commitment without importing prohibited observables, including identity "
            "inference, mental-state inference, behavioral inference, preference mining, or "
            "retrospective motive attribution.\n"
            "Non-operational containment: the representation does not become an operational mandate "
            "by interpretation. Where a reader attempts to convert representational language into "
            "integration requirements, monitoring requirements, enforcement posture, scoring, "
            "sanctions, or outcome guarantees, the conversion is inadmissible.\n\n"
            "Where any admissibility condition cannot be satisfied without prohibited inference or "
            "operational substitution, the classification outcome SHALL be Refusal (Terminal). "
            "Refusal is terminal.\n\n"
            "Authorized Representation Classes (Sealed Taxonomy). For the purposes of this volume, "
            "authorized representations SHALL be classified into one or more of the following "
            "classes. These classes are representational, not interface-level.\n\n"
            "PolicyRepresentation: explicit policy text stating declared constraints, declared "
            "objectives, declared prohibitions, or declared interpretive limits within scope. Policy "
            "Representations SHALL NOT be reinterpreted as implementation requirements, monitoring "
            "directives, enforcement posture, certification criteria, or outcome guarantees.\n\n"
            "ContractRepresentation: explicit contractual language or binding commitments admitted "
            "within the received record, including covenants, binding constraints, and binding "
            "limits. ContractRepresentations MAY include binding non-claims and scope limits where "
            "explicitly stated. They SHALL NOT be expanded by implication into enforcement "
            "mechanisms, sanctions regimes, or operational obligations beyond what is explicitly "
            "represented.\n\n"
            "DeclaredConstraintRepresentation: an explicit constraint statement admitted as intent — "
            "a declared permission, prohibition, boundary, or invariant. Declared constraints SHALL "
            "NOT be converted into telemetry mandates, scoring regimes, monitoring requirements, or "
            "optimization goals.\n\n"
            "ScopeStatementRepresentation: an explicit statement that bounds what is included, "
            "excluded, or refused — scope limits, exclusions, non-claims, and refusal boundaries. "
            "Scope statements SHALL be treated as binding interpretive constraints. Where a scope "
            "statement excludes a class of interpretation (e.g., identity inference, mental-state "
            "inference, behavioral inference, outcome guarantees), that exclusion is not negotiable "
            "and cannot be bypassed by 'pragmatic' re-read.\n\n"
            "CitationContractRepresentation: explicit citation, derivative-use, and transformation "
            "constraint language that governs how the doctrine may be referenced without exceeding "
            "jurisdiction. Citation constraints are interpretive limits. They SHALL NOT be treated "
            "as a policy regime, a compliance program, or an enforcement posture. Where citation "
            "constraints are violated by a proposed use, the doctrine's lawful output is Refusal "
            "(Terminal).\n\n"
            "Class Integrity (Non-Capture Rules). For all classes above: authorized representations "
            "SHALL be treated as textual commitments within a sealed domain of meaning, not as "
            "proxies for behavior, identity, mental state, or hidden objectives. No representation "
            "SHALL be treated as authorization to infer 'true intent' behind the representation. No "
            "representation SHALL be extended by post hoc narrative to resolve ambiguity, "
            "contradiction, or missing prerequisites.\n\n"
            "Conflict, Ambiguity, and Missing Authorization (Boundary Rule). If two or more "
            "authorized representations appear to conflict, the conflict SHALL NOT be resolved by "
            "preference, assumed hierarchy, institutional convenience, or inferred motive. Where "
            "conflict, ambiguity, or missing authorization prevents formation of a coherent intent "
            "basis without inference, classification SHALL terminate as Refusal (Terminal). Refusal "
            "is terminal."
        ),
    },
    {
        "ref": "equivalence-relation",
        "heading": "Representational Equivalence Relation",
        "text": (
            "The domain equivalence relation (written ≡) specifies when two authorized "
            "representations may be treated as the same intent-domain meaning for purposes of "
            "classification — without importing mechanisms, identity inference, behavioral inference, "
            "or outcome claims. Domain equivalence exists to preserve Intent Symmetry (Volume I) "
            "across representational forms. It prevents conservation claims from collapsing into "
            "format dependence, rhetorical substitution, or post hoc narrative.\n\n"
            "Definition (sealed; representational). Let r1, r2 be authorized representations. "
            "r1 ≡ r2 SHALL hold only if all of the following are satisfied:\n"
            "1. Authorization holds for both: Auth(r1) and Auth(r2) are satisfied under Intent "
            "(sealed) and the Authorized Representation admissibility conditions. No equivalence "
            "claim is admissible where either representation is not itself admissible as intent "
            "representation.\n"
            "2. Equivalent meaning commitments (within bound): the admissible meaning commitments "
            "of r1 and r2, as constrained by Interp(), are the same within the allowable bound of "
            "the intent-domain. 'Within bound' denotes an admissible semantic boundary, not a "
            "metric and not an operational test.\n"
            "3. No prohibited observables are required: the equivalence claim is stated without "
            "identity inference, mental-state inference, behavioral inference, preference mining, "
            "retrospective motive attribution, or any substitute inference introduced to force "
            "equivalence.\n"
            "4. No operational substitution is required: the equivalence claim does not depend on "
            "implementation details, instrumentation, monitoring posture, enforcement posture, "
            "scoring, audit regimes, or outcomes. If equivalence requires 'what the system did' to "
            "be true, equivalence is out-of-scope.\n\n"
            "Where any condition above cannot be satisfied within the sealed intent-domain, the "
            "lawful output is Refusal (Terminal). Refusal is terminal.\n\n"
            "Equivalence relation posture (representational; non-operational). Within this volume, "
            "≡ is treated as an equivalence relation over admissible representations where it can "
            "be stated lawfully. This does not claim computability or automation. It asserts only "
            "the representational posture required for consistent classification: if equivalence is "
            "asserted, it SHALL be coherent and stable as a domain relation, not a rhetorical "
            "convenience.\n\n"
            "What equivalence permits (and what it does not). If r1 ≡ r2 holds, then either "
            "representation MAY be used as a domain-equivalent statement of the same admitted "
            "meaning commitments for classification purposes. However: domain equivalence does not "
            "authorize replacing sealed scope limits, non-claims, or refusal boundaries with 'close "
            "enough' paraphrases; domain equivalence does not authorize compressing or omitting "
            "binding constraints; domain equivalence does not authorize turning representational "
            "constraints into operational mandates; domain equivalence does not authorize outcome "
            "claims ('equivalent intent implies equivalent behavior' is inadmissible).\n\n"
            "What domain equivalence is not (clarifying; non-operational). Domain equivalence is "
            "not: functional equivalence (does not claim two systems behave the same); behavioral "
            "equivalence (does not claim the same outputs or actions will occur); outcome "
            "equivalence (does not claim the same results, harms, or benefits); compliance "
            "equivalence (does not claim certification, conformity, or audit pass); hidden-intent "
            "equivalence (does not authorize the claim that two texts 'really mean' the same thing "
            "behind what they say). Domain equivalence is representational: it states only that two "
            "authorized representations, interpreted under Interp() within the sealed intent-domain, "
            "carry the same admissible meaning commitments within bound.\n\n"
            "Failure posture (binding). Where an equivalence claim would require importing "
            "prohibited observables, treating behavior as evidence of intent, treating identity as "
            "evidence of intent, resolving ambiguity by narrative substitution, or operationalizing "
            "the doctrine to make equivalence 'true,' the doctrine does not degrade to "
            "approximation. Refusal (Terminal). Refusal is terminal.\n\n"
            "Interpretation Relation (Non-Operational). The ontology's interpretation relation "
            "Interp() is the representational relation by which authorized intent representations "
            "are taken to carry admissible meaning commitments inside the sealed intent-domain. "
            "Interp() operates only over authorized representations (r ∈ R), yields only admissible "
            "meaning commitments internal to the intent-domain, and explicitly excludes identity "
            "inference, mental-state inference, preference mining, behavioral attribution, and "
            "retrospective motive attribution. Interpretation in this volume is not 'what an actor "
            "intended.' It is not 'what a system did.' It is a representational relation constrained "
            "to what is explicitly authorized in the received record. Where interpretation cannot be "
            "stated within authorized representations without prohibited inference or operational "
            "substitution, the lawful output is Refusal (Terminal). Refusal is terminal."
        ),
    },
    {
        "ref": "admissibility-posture",
        "heading": "Admissibility Posture (Volume II)",
        "text": (
            "This trilogy classifies only what can be stated within authorized representations. If a "
            "proposed mapping requires prohibited observables — psychological attribution, identity "
            "inference, behavioral inference, or narrative substitution — or if it requires "
            "operationalization to be made meaningful, the classification outcome is not 'partial "
            "credit,' not 'best effort,' and not 'approximate compliance.' The outcome is Refusal "
            "(Terminal). Refusal is not a failure mode to be optimized away. It is a boundary "
            "condition that protects the doctrine's jurisdiction.\n\n"
            "Read this volume as a jurisdictional object, not as a program. It is canonical in the "
            "limited sense that it defines what its terms mean and what its labels mean. It does not "
            "authorize mechanisms, interfaces, enforcement, monitoring, scoring, or outcome claims. "
            "It does not authorize identity inference, mental-state inference, or behavioral "
            "inference. All key terms are sealed: they refer only to authorized representations — "
            "explicit policies, contracts, declared constraints, scope statements, and citation/use "
            "constraints. All non-claims are binding: where this volume refuses mechanisms, "
            "interfaces, enforcement posture, telemetry, outcome guarantees, or inference, those "
            "refusals are not negotiable and must not be reinterpreted as 'implied requirements,' "
            "'best practices,' or 'implementation intent.'\n\n"
            "Conserving / Non-Conserving Labels (Ontology-Level). The labels Conserving and "
            "Non-Conserving are ontology-level classification outputs applied to representational "
            "transformations within a sealed intent-domain. They are not scores, rankings, maturity "
            "levels, compliance attestations, or performance claims. They do not certify systems, "
            "processes, governance posture, safety, or ethical outcomes.\n\n"
            "A Conserving classification SHALL be asserted only when all of the following are "
            "satisfied within the sealed intent-domain: authorized origin and destination — the "
            "representations at issue are admissible under Intent (sealed); interpretation remains "
            "sealed — meaning commitments used to justify conservation are admissible under Interp() "
            "without identity inference, mental-state inference, behavioral inference, or narrative "
            "supplementation; drift remains within bound — the transformation remains within the "
            "allowable drift bound of the intent-domain (WithinBound(T, r)), including preservation "
            "of scope integrity, non-claim integrity, constraint integrity, and anti-proxy integrity; "
            "and trace representability holds — the conserving claim is trace-representable as a "
            "finite, citable representational record.\n\n"
            "A transformation is Non-Conserving when it violates one or more binding constraints of "
            "the sealed intent-domain in a way that is representationally stateable — i.e., the "
            "violation can be identified as an ontology-level deformation without importing "
            "prohibited observables or operational substitution. Non-conservation includes: scope "
            "creep, non-claim erosion, constraint inflation or inversion, proxy substitution, and "
            "loss of trace representability where the deformation can be stated as a representational "
            "break.\n\n"
            "Refusal (Terminal) as Out-of-Jurisdiction Object. Refusal (Terminal) is a sealed "
            "classification output and a jurisdiction boundary condition. It denotes that a claim "
            "cannot be lawfully classified without exceeding scope, importing prohibited observables, "
            "or substituting operational facts for representational commitments. Refusal is not a "
            "degraded label. It is not partial compliance. It is not a temporary status pending "
            "later implementation. It is the doctrine's lawful closure when admissibility "
            "prerequisites are not met.\n\n"
            "Refusal SHALL be the admissible output when any of the following conditions hold: "
            "(A) missing or disputed authorization — the intent basis cannot be formed without "
            "inference; (B) out-of-domain expression — the claim cannot be stated as a "
            "representational relation within the sealed intent-domain; (C) prohibited observables "
            "are required — any step requires identity inference, mental-state inference, behavioral "
            "inference, preference mining, or retrospective motive attribution; (D) operational "
            "substitution is demanded — a request seeks to convert the doctrine into mechanism, "
            "interface, operational playbook, monitoring requirement, scoring system, enforcement "
            "posture, sanctions regime, audit program, certification standard, or outcome guarantee; "
            "(E) outcome capture is implied or required — a claim depends on outcomes as the basis "
            "for classification; (F) semantic altitude downgrade is attempted — a reading attempts "
            "to downgrade this volume's law/ontology altitude into operational mandates, governance "
            "requirements, or compliance posture by implication.\n\n"
            "No-Mechanism / No-Interface / No-Enforcement Guardrails (Normative). This volume is "
            "classification-only and non-operational. A request SHALL be refused where it attempts "
            "to convert this volume into: runtime controls, tools or toolchains, orchestration "
            "logic, instrumentation, monitoring, logging, telemetry, surveillance, scoring or "
            "certification systems (No-Mechanism); APIs, schemas, data flows, event flows, "
            "observability surfaces, or any integration specification (No-Interface); sanctions, "
            "penalties, escalation paths, mandatory governance posture, compliance mandates, or any "
            "punitive use of classification labels (No-Enforcement); or safety guarantees, ethical "
            "sufficiency, regulatory sufficiency, liability insulation, behavioral control, or "
            "predictive assurance (No-Outcome Guarantee).\n\n"
            "Semantic Altitude Irreversibility (Carry-forward). Once meaning has been sealed at "
            "law/ontology altitude in this trilogy, later readings SHALL NOT downgrade, "
            "reinterpret, or 'translate' that meaning into operational obligations, implementation "
            "requirements, enforcement posture, monitoring or telemetry regimes, scoring systems, "
            "certification programs, or outcome claims. The seal is one-way. Refusal is terminal."
        ),
    },
    {
        "ref": "drift-bounds",
        "heading": "Drift Bounds and Closure",
        "text": (
            "Drift denotes ambiguity growth, proxy substitution, or untraceability that increases "
            "interpretive instability within the sealed intent-domain. Drift is an ontology-level "
            "deformation: it names a condition under which the intent-domain's representational "
            "commitments can no longer be carried forward without silent change. It is not an "
            "empirical performance claim. It is not 'model drift.' It is not a monitoring category. "
            "It is a doctrine-level admissibility construct used to preserve jurisdiction.\n\n"
            "Drift SHALL be understood as a failure of stable representational meaning inside the "
            "sealed domain, expressed by one or more of the following:\n\n"
            "Ambiguity growth. A representation becomes increasingly elastic under repeated "
            "interpretation, paraphrase, or re-framing — until what was once explicit scope or "
            "constraint can be re-read as optional, implied, or expandable. Ambiguity growth is a "
            "drift condition because it creates the pretext for downstream substitution: when "
            "meaning is no longer determinate, institutions tend to 'complete' it by convenience, "
            "urgency, or power. This trilogy does not authorize that completion.\n\n"
            "Proxy substitution. An authorized representation is displaced by a proxy that is not "
            "authorized by the intent basis — most commonly by importing prohibited observables "
            "(identity-derived intent, mental-state inference, behavioral inference) or by "
            "substituting operational facts (telemetry, outcomes, implementation details) for "
            "representational commitments. Proxy substitution is drift because it changes the "
            "ontology: the doctrine's object is replaced, even while the word 'intent' is retained.\n\n"
            "Untraceability (representational). A transformation or interpretive move cannot be "
            "stated as an in-domain representational mapping from authorized representation to "
            "authorized representation. Untraceability here is not a logging concern; it is a "
            "meaning concern. It names the point at which the representational pathway required to "
            "justify a conservation claim cannot be articulated without importing inference, "
            "narrative supplementation, or operational substitution.\n\n"
            "Drift is used only to govern admissibility posture. It does not prescribe operational "
            "controls, monitoring systems, audits, enforcement posture, scoring, sanctions, or "
            "remedies. Any attempt to interpret drift as a call for instrumentation or enforcement "
            "exceeds jurisdiction.\n\n"
            "Drift Bound Relation (Admissibility Predicate). A drift bound is an admissibility "
            "predicate — written WithinBound(T, r) — asserting that a representational "
            "transformation T applied to an authorized representation r does not exceed the "
            "allowable drift bound of the sealed intent-domain. WithinBound() exists to formalize "
            "Volume I's Drift Containment constraint as an ontology predicate. It stabilizes "
            "classification by preventing 'conservation' from being claimed after meaning has been "
            "silently altered through ambiguity growth, scope creep, proxy substitution, or erosion "
            "of binding non-claims.\n\n"
            "WithinBound(T, r) is admissible only when the following can be stated entirely within "
            "authorized representations: the input representation r is authorized (Auth(r)); the "
            "transformed representation T(r) is stated as a representational object (not as a "
            "mechanism, interface, or runtime behavior); and the admissible meaning commitments "
            "carried by T(r) remain within the domain's allowable semantic variation relative to r. "
            "The allowable drift bound is semantic and doctrinal. It is intentionally conservative. "
            "It is bounded by: scope integrity (no enlargement of scope beyond what is explicitly "
            "authorized); non-claim integrity (no deletion, softening, or reclassification of "
            "binding non-claims); constraint integrity (no unauthorized addition, removal, inversion, "
            "or inflation of commitments); and anti-proxy integrity (no substitution of identity, "
            "mental state, behavior, outcomes, or institutional preference as a surrogate for "
            "authorized representation).\n\n"
            "WithinBound(T, r) SHALL NOT be asserted where the claim depends on prohibited "
            "observables or on operational substitution (implementation details, telemetry, "
            "monitoring posture, enforcement posture, scoring, audits, sanctions, or outcomes). "
            "Where WithinBound(T, r) is false and the violation can be stated within the sealed "
            "intent-domain as a representational drift, the transformation is classifiable as "
            "Non-Conserving. Where WithinBound(T, r) cannot be stated without prohibited inference, "
            "narrative supplementation, or operational substitution, the proper outcome is Refusal "
            "(Terminal). No metric implied (binding): WithinBound() does not imply any measurement "
            "program, telemetry expansion, monitoring regime, scoring system, auditing procedure, "
            "certification scheme, or operational thresholding.\n\n"
            "Trace Representability Relation. Trace representability is an admissibility relation "
            "asserting that the path from authorized representations to a classification label is "
            "expressible in-domain as a finite, citable representational record — without prohibited "
            "observables, unstated premises, or outcome reasoning. A classification claim is "
            "trace-representable only if there exists a finite representational record C such that: "
            "authorized origin — the record identifies the specific authorized representations "
            "r ∈ R from which the claim proceeds, with Auth(r) satisfied; in-domain steps — the "
            "record expresses the intermediate representational moves as in-domain relations, "
            "without substituting implementation facts, institutional authority, or behavioral "
            "evidence for representational commitments; citable closure — the record terminates in "
            "a classification label in a way that can be cited as a representational derivation "
            "within the sealed intent-domain; no prohibited observables; and no unstated premises.\n\n"
            "Trace representability is a doctrinal admissibility constraint, not an evidentiary "
            "regime. It is a constraint on what may be claimed as conserving, and a stabilizer "
            "preventing semantic laundering (where labels are asserted without a lawful "
            "representational pathway). It is not a requirement to 'track,' 'log,' or 'instrument' "
            "systems. It is not a monitoring or surveillance posture. It is not a compliance or "
            "audit mandate. Where trace representability cannot be satisfied without identity "
            "inference, mental-state inference, behavioral inference, or outcome reasoning, the "
            "admissible outcome is Refusal (Terminal). Refusal is terminal.\n\n"
            "Closure. This volume's ontology closes against interpretive capture by refusing to "
            "stretch under the following predictable pressure modes: mandate capture (turning "
            "doctrine into obligations), mechanism pull (converting ontology into runtime technique), "
            "interface pull (treating representational relations as integration requirements), "
            "enforcement capture (converting labels into governance authority), certification "
            "capture (treating conformance as compliance status), outcome capture (treating "
            "conserving labels as guarantees), inference capture (importing identity or behavioral "
            "attribution), scope laundering (expanding the intent-domain by implication), non-claim "
            "laundering (weakening binding non-claims), and refusal dilution (reframing refusal as "
            "negotiable). Where any such demand cannot be refused within the sealed intent-domain, "
            "the lawful closure condition is Refusal (Terminal). Refusal is terminal."
        ),
    },
]


def main():
    if not BUNDLE.exists():
        print("ERROR: data/corpus-bundle.json not found. Run build-registry-bundle.ts first.")
        raise SystemExit(1)

    bundle = json.loads(BUNDLE.read_text(encoding="utf-8"))

    patched = False
    for artifact in bundle["artifacts"]:
        if artifact["id"] == "UFTAGP-COI-002":
            artifact["sections"] = SECTIONS
            artifact["curated"] = True
            patched = True
            print(f"Patched UFTAGP-COI-002 — {len(SECTIONS)} sections, curated=True")
            break

    if not patched:
        print("WARNING: UFTAGP-COI-002 not found in bundle — adding it.")
        bundle["artifacts"].append({
            "id": "UFTAGP-COI-002",
            "title": "Conservation of Intent — Volume II: Intent-Domain Ontology + Transformational Relations",
            "curated": True,
            "sections": SECTIONS,
        })

    BUNDLE.write_text(json.dumps(bundle, indent=2), encoding="utf-8")
    print("corpus-bundle.json updated.")
    print("Verify: python -c \"import json; b=json.load(open('data/corpus-bundle.json')); "
          "[print(a['id'], len(a['sections'])) for a in b['artifacts']]\"")
    print("Expected: UFTAGP-COI-002 5")


if __name__ == "__main__":
    main()
